apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "8008"
      port: 8008
      targetPort: 8000
  selector:
    io.kompose.service: api
