apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DSHOST
              value: store
            - name: DSPORT
              value: "50050"
            - name: FASTAPI_ROOT_PATH
              value: /raw/
            - name: FORWARDED_ALLOW_IPS
              value: 127.0.0.1
            - name: GRPC_MAX_MESSAGE_SIZE
              value: "-1"
            - name: GUNICORN_CMD_ARGS
              value: --bind 0.0.0.0:8000 --workers=4 --access-logfile -
          image: ghcr.io/eumetnet/e-soh/api:0.3.0
          livenessProbe:
            exec:
              command:
                - curl --fail http://localhost:8000/health || exit 1
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
