apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: data
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_USER
              value: postgres
          image: kartoza/postgis:15
          livenessProbe:
            exec:
              command:
                - /healthcheck_postgis_uptime.sh postgresql://postgres:mysecretpassword@localhost/data 10 second
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
          name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: ts-data-raw
            - mountPath: /healthcheck_postgis_uptime.sh
              name: db-claim1
      restartPolicy: Always
      volumes:
        - name: ts-data-raw
          persistentVolumeClaim:
            claimName: ts-data-raw
        - name: db-claim1
          persistentVolumeClaim:
            claimName: db-claim1
