apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ingest
  name: ingest
spec:
  ports:
    - name: "8009"
      port: 8009
      targetPort: 8001
  selector:
    io.kompose.service: ingest
