apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ingest
  name: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ingest
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ingest
    spec:
      containers:
        - env:
            - name: DSHOST
              value: store
            - name: DSPORT
              value: "50050"
            - name: FASTAPI_ROOT_PATH
              value: /raw/ingest/
            - name: GUNICORN_CMD_ARGS
              value: --bind 0.0.0.0:8001 --workers=8 --access-logfile -
            - name: MQTT_HOST
              value: iot.esoh.met.no
            - name: MQTT_PORT
              value: "8883"
            - name: MQTT_TLS
              value: "True"
            - name: MQTT_TOPIC_PREPEND
              value: raw-obs
          image: ghcr.io/eumetnet/e-soh/ingest:0.3.0
          name: ingest
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
