apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: prometheus-postgres-exporter
  name: prometheus-postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus-postgres-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: prometheus-postgres-exporter
    spec:
      containers:
        - args:
            - --collector.stat_statements
            - --collector.stat_user_tables
            - --collector.stat_activity_autovacuum
          env:
            - name: DATA_SOURCE_PASS
              value: mysecretpassword
            - name: DATA_SOURCE_URI
              value: db:5432/data
            - name: DATA_SOURCE_USER
              value: postgres
          image: quay.io/prometheuscommunity/postgres-exporter
          name: prometheus-postgres-exporter
          ports:
            - containerPort: 9187
              protocol: TCP
          volumeMounts:
            - mountPath: /postgres_exporter.yml
              name: prometheus-postgres-exporter-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: prometheus-postgres-exporter-claim0
          persistentVolumeClaim:
            claimName: prometheus-postgres-exporter-claim0
            readOnly: true
