apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: store
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: store
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: store
    spec:
      containers:
        - env:
            - name: CLEANUPINTERVAL
            - name: HITIME
              value: "-600"
            - name: LOTIME
              value: "86400"
            - name: PGHOST
              value: db
            - name: PGPORT
              value: "5432"
            - name: PUTOBSLIMIT
          image: ghcr.io/eumetnet/e-soh/datastore:0.3.0
          livenessProbe:
            exec:
              command:
                - exit $(/bin/grpc_health_probe -addr=localhost:50050)
            failureThreshold: 15
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 1
          name: store
      restartPolicy: Always
