apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ts-data-raw
  name: ts-data-raw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
